### ISSUE TITLE
Typo in 'About' line of project

### ISSUE THREAD

**Issue by deining** [tomasguisasola/dado#2]
On this GitHub project website, the `About` line on the top right states:

```
Dado is a package that offers somre facilities over LuaSQL connection objects.
```
There is a typo, `somre` should be changed to `some`.

**Comment by tomasguisasola** [comment]
Sorry, but I cannot find the "About line on the top right".  I searched for it with grep over the entire repository but couldn't find any "somre".  Would you mind be more specific?

**Comment by tomasguisasola** [comment]
Forget it!  I have just found it and corrected it.

Thanks!
